# Generated by Django 4.1.6 on 2023-02-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0006_alter_post_view"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post", name="title", field=models.CharField(max_length=50),
        ),
    ]
