# Generated by Django 4.1.6 on 2023-02-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0007_alter_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
